apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-api   
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  hospital-api
  template:
    metadata:
      labels:
        app:  hospital-api
    spec:
      containers:
      - name: hospital-api
        image: dockerstore.azurecr.io/hospital:158
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            httpHeaders:
            - name: X-Custom-Header
              value: Awesome
          initialDelaySeconds: 90
          periodSeconds: 10
        env:              
        - name: "DeviceName" 
          value: "aStrangeDevice"        
      imagePullSecrets:
      - name: topsecretregistryconnection
---
kind: Service
apiVersion: v1
metadata:
  name: hospital-api-service   
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80      
  selector:
    app:  hospital-api
