apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-api   
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  hospital-api
  template:
    metadata:
      labels:
        app:  hospital-api
    spec:
      containers:
      - name: hospital-api
        image: dockerstore.azurecr.io/hospital:##BUILD_ID##
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        env:              
        - name: SqlConnectionString
          valueFrom:
            secretKeyRef:
              name: thebigsecret
              key: SqlConnectionString       
      imagePullSecrets:
      - name: topsecretregistryconnection
---
kind: Service
apiVersion: v1
metadata:
  name: hospital-api-service   
  namespace: nm
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80      
  selector:
    app:  hospital-api
